// The self-contained static HTML export formatter (see docs/export-format.md):
// built from the shared `ExportModel` plus a caller-supplied `css` string
// (domain code cannot import `src/ui/tokens.ts` — see docs/architecture.md —
// so the composable layer builds the token stylesheet and passes it in). No
// external requests, no scripts: the file must open and render on its own.
import { describe, expect, it } from 'vitest'
import golden from '../../tests/fixtures/export/basic-report.html?raw'
import { formatExportHtml } from './exportHtml'
import { buildExportModel } from './exportModel'
import { updateWorking } from './analysis'
import { defaultFilter } from './types'
import { baseExportAnalysis, withExportOptions } from '../../tests/fakes/exportFixtures'

const NOW = new Date('2026-09-23T14:05:00')
// Deterministic stand-in for the real token stylesheet the composable layer
// would pass in: fixed, made-up custom properties, so the golden fixture
// never depends on src/ui/tokens.ts's own values or wording.
const CSS = ':root {\n  --color-bg: #fff;\n}\n\n@media (prefers-color-scheme: dark) {\n  :root {\n    --color-bg: #000;\n  }\n}'

const GENERATED_LINE_RE = /(<strong>Generated:<\/strong> )[^<]*/
function normalizeGenerated(html: string): string {
  return html.replace(GENERATED_LINE_RE, '$1<TIMESTAMP>')
}

describe('formatExportHtml — golden file (see docs/export-format.md)', () => {
  it('matches tests/fixtures/export/basic-report.html byte-for-byte, apart from the Generated line', () => {
    const analysis = withExportOptions(
      updateWorking(baseExportAnalysis(), { filter: { ...defaultFilter(), relevanceMin: 50 } }, '2026-09-01T00:00:00Z'),
      {
        orderMode: 'custom',
        scope: 'filtered',
        order: [
          { key: 'priority', direction: 'desc' },
          { key: 'effort', direction: 'asc' },
        ],
        includeDismissed: true,
        includeUnclassified: true,
        includeConfidence: true,
        includeUrls: true,
      },
    )

    const model = buildExportModel(analysis, analysis.working.exportOptions, NOW)
    const actual = formatExportHtml(model, CSS)
    expect(normalizeGenerated(actual)).toBe(golden)
  })
})

describe('formatExportHtml — self-contained document', () => {
  it('has a doctype, charset meta, and a title', () => {
    const analysis = baseExportAnalysis()
    const html = formatExportHtml(buildExportModel(analysis, analysis.working.exportOptions, NOW), CSS)
    expect(html.startsWith('<!doctype html>')).toBe(true)
    expect(html).toContain('<meta charset="UTF-8" />')
    expect(html).toMatch(/<title>.*<\/title>/)
  })

  it('embeds the given CSS verbatim, including the dark-mode media query', () => {
    const analysis = baseExportAnalysis()
    const html = formatExportHtml(buildExportModel(analysis, analysis.working.exportOptions, NOW), CSS)
    expect(html).toContain(CSS)
  })

  it('ends with exactly one trailing newline', () => {
    const analysis = baseExportAnalysis()
    const html = formatExportHtml(buildExportModel(analysis, analysis.working.exportOptions, NOW), CSS)
    expect(html.endsWith('\n')).toBe(true)
    expect(html.endsWith('\n\n')).toBe(false)
  })

  it('has no external requests: no <link>, no <script>, no @import, no font/CDN references', () => {
    const analysis = baseExportAnalysis()
    const html = formatExportHtml(buildExportModel(analysis, analysis.working.exportOptions, NOW), CSS)
    expect(html).not.toMatch(/<link/i)
    expect(html).not.toMatch(/<script/i)
    expect(html).not.toMatch(/@import/i)
    expect(html).not.toMatch(/fonts\.googleapis|fonts\.gstatic|cdn\.|unpkg\.com|jsdelivr/i)
  })

  it('still links out to the issue itself when includeUrls is on (a hyperlink, not a resource fetch)', () => {
    const analysis = withExportOptions(baseExportAnalysis(), { includeUrls: true })
    const html = formatExportHtml(buildExportModel(analysis, analysis.working.exportOptions, NOW), CSS)
    expect(html).toContain('href="https://github.com/acme/widgets/issues/812"')
  })

  it('has a footer crediting Issue Classifier', () => {
    const analysis = baseExportAnalysis()
    const html = formatExportHtml(buildExportModel(analysis, analysis.working.exportOptions, NOW), CSS)
    expect(html).toMatch(/<footer>[\s\S]*Generated by Issue Classifier[\s\S]*<\/footer>/)
  })
})

describe('formatExportHtml — escaping (titles and bodies are third-party text)', () => {
  it('renders a title containing <script> as escaped text, never as a live tag', () => {
    const analysis = baseExportAnalysis()
    analysis.rows[0].issue.title = 'Crash <script>alert(1)</script> now'
    const html = formatExportHtml(buildExportModel(analysis, analysis.working.exportOptions, NOW), CSS)
    expect(html).not.toContain('<script>alert(1)</script>')
    expect(html).toContain('&lt;script&gt;alert(1)&lt;/script&gt;')
  })

  it('escapes an ampersand and quotes in a title', () => {
    const analysis = baseExportAnalysis()
    analysis.rows[0].issue.title = 'A & B "quoted"'
    const html = formatExportHtml(buildExportModel(analysis, analysis.working.exportOptions, NOW), CSS)
    expect(html).toContain('A &amp; B &quot;quoted&quot;')
  })
})

describe('formatExportHtml — includeBodies', () => {
  it('adds no <details> at all when includeBodies is false (the default)', () => {
    const analysis = withExportOptions(baseExportAnalysis(), { includeBodies: false })
    const html = formatExportHtml(buildExportModel(analysis, analysis.working.exportOptions, NOW), CSS)
    expect(html).not.toContain('<details>')
  })

  it('adds a <details> with the escaped, trimmed body per row when includeBodies is true', () => {
    const analysis = withExportOptions(baseExportAnalysis(), { includeBodies: true })
    const html = formatExportHtml(buildExportModel(analysis, analysis.working.exportOptions, NOW), CSS)
    expect(html).toContain('<details>')
    expect(html).toContain('Steps to reproduce:')
  })

  it('omits <details> for a row whose body is empty even when includeBodies is true', () => {
    const analysis = withExportOptions(baseExportAnalysis(), { includeBodies: true })
    analysis.rows[1].issue.body = '   '
    const html = formatExportHtml(buildExportModel(analysis, analysis.working.exportOptions, NOW), CSS)
    const detailsCount = (html.match(/<details>/g) ?? []).length
    expect(detailsCount).toBe(1) // only #812 (the one with a non-blank body)
  })
})

describe('formatExportHtml — level chips', () => {
  it('renders each classified dimension as a text chip with a coloured dot, not an image', () => {
    const analysis = baseExportAnalysis()
    const html = formatExportHtml(buildExportModel(analysis, analysis.working.exportOptions, NOW), CSS)
    expect(html).not.toContain('<img')
    expect(html).toMatch(/<span class="chip chip--high">[\s\S]*?HIGH<\/span>/)
  })

  it('renders "—" for a dimension on an unclassified row', () => {
    const analysis = baseExportAnalysis()
    const html = formatExportHtml(buildExportModel(analysis, analysis.working.exportOptions, NOW), CSS)
    expect(html).toContain('<td>—</td>')
  })
})
