// local-issue-classifier — typed domain model + defaultX() factories + STORAGE_KEYS.
// Plain serializable interfaces, no Vue, no fetch, no storage,
// no browser APIs: the clock and randomness are always injected by the caller.
import type { HardwareOverride } from './hardware'

import { defaultProviderConfig } from './provider'
import type { ProviderConfig } from './provider'

import { DEFAULT_VISIBLE_COLUMNS } from './columns'
import type { TableColumnId } from './columns'

/** The one place the default Jev model name lives (Preferences.jevModel, Jev client). */
export const DEFAULT_JEV_MODEL = 'jev-latest'

// ── Repository & issues ──────────────────────────────────────────────
export interface RepoRef {
  owner: string
  repo: string
}

export interface Repo {
  ref: RepoRef
  fullName: string // "owner/repo"
  description: string | null
  topics: string[]
  defaultBranch: string
  isPrivate: boolean
  hasIssues: boolean
  openIssuesCount: number // GitHub's count includes PRs; informational only
  htmlUrl: string
}

export type IssueState = 'open' | 'closed'

export interface IssueComment {
  id: number
  author: string // login, or "ghost" when the user was deleted
  authorAssociation: string // OWNER | MEMBER | CONTRIBUTOR | NONE | ...
  createdAt: string // ISO 8601
  body: string
}

export interface Issue {
  number: number
  title: string
  body: string // '' when null
  state: IssueState
  stateReason: string | null // completed | not_planned | reopened | null
  labels: string[]
  author: string
  authorAssociation: string
  createdAt: string
  updatedAt: string
  closedAt: string | null
  commentCount: number // GitHub's `comments` field
  comments: IssueComment[] // may be a subset; see commentsTruncated
  commentsTruncated: boolean
  commentsFetched: boolean // false when comments were skipped
  reactionsTotal: number
  htmlUrl: string
}

// ── Project context sent to Jev ──────────────────────────────────────
export interface ProjectContext {
  name: string // repo full name
  description: string | null // repo description
  topics: string[]
  manifest: {
    source: 'package.json' | 'pyproject.toml' | 'Cargo.toml' | 'go.mod' | null
    name: string | null
    description: string | null
  }
  readmeExcerpt: string | null // trimmed, see §4.3
  contributingExcerpt: string | null
  docsIndex: string[] // file/dir names under docs/, max 40
}

// ── Classification ───────────────────────────────────────────────────
export type Level = 'low' | 'medium' | 'high'
export type Dimension = 'complexity' | 'criticality' | 'effort'

export interface ScoreDimension {
  level: Level // from Math.round(score), §4.4
  score: number // raw Jev score, 0..2 (continuous)
  confidence?: number // 0..1, from Jev; optional so providers without it still map
  probabilities: [number, number, number] // [low, medium, high]
}

export interface RelevanceResult {
  value: number // 0..100 integer, §4.4
  score: number // raw Jev score, 0..4
  confidence?: number
  probabilities: [number, number, number, number, number]
}

export type IssueKind = 'bug' | 'feature' | 'documentation' | 'question' | 'maintenance' | 'other'

export interface Classification {
  complexity: ScoreDimension
  criticality: ScoreDimension
  effort: ScoreDimension
  relevance: RelevanceResult
  kind: { choice: IssueKind; confidence?: number } // speculative extra, §4.2
  minConfidence?: number // min of the available main confidences; absent when none
  model: string // versioned id from the response, e.g. "jev-1.13.0"
  questionsVersion: number // QUESTIONS_VERSION at classification time
  issueUpdatedAt: string // Issue.updatedAt at classification time
  classifiedAt: string // ISO 8601
  inputTokens: number
}

export type ClassificationStatus = 'unclassified' | 'pending' | 'done' | 'error' | 'stale'

export interface IssueRow {
  issue: Issue // stored form: body and comments already trimmed, §4.8
  status: ClassificationStatus
  classification: Classification | null
  error: string | null
  sourceStatus: 'present' | 'missing' // 'missing' = absent from the latest refresh, §2.3
}

// ── Analysis: one persisted repository run (§3.1) ────────────────────
export interface AnalysisWorkingState {
  filter: IssueFilter
  tableSort: ExportOrder // multi-key table sort ("reorder"), persisted
  exportOptions: ExportOptions // export order + flags, persisted
  priorityWeights: PriorityWeights // §4.9, persisted
  dismissed: number[] // issue numbers hidden from the working list
  showDismissed: boolean
  expandedIssue: number | null // UI convenience; safe to lose
  visibleColumns?: TableColumnId[] // design v2 (see useColumns); tolerant loading normalizes this
  // pinned?: number[]          // optional, not in v1 (§2.5 item 6)
}

export interface Analysis {
  schemaVersion: 1
  id: string // generated by an injected id factory (crypto.randomUUID)
  name: string // default "owner/repo (open)"
  repo: Repo
  stateFilter: 'open' | 'closed' | 'all'
  createdAt: string
  updatedAt: string // any change, incl. working state
  fetchedAt: string // last successful GitHub fetch
  commentsFetched: boolean
  projectContext: ProjectContext
  rows: IssueRow[] // keyed by issue.number, unique
  working: AnalysisWorkingState
}

/** Small index entry so Home can list analyses without parsing each one. */
export interface AnalysisSummary {
  id: string
  name: string
  repoFullName: string
  stateFilter: Analysis['stateFilter']
  fetchedAt: string
  updatedAt: string
  counts: { total: number; classified: number; stale: number; dismissed: number; missing: number }
  approxBytes: number // serialized size of the analysis entry
}

// ── Secrets (IN MEMORY ONLY — never serialized, never persisted) ─────
export interface Secrets {
  jevApiKey: string // '' = absent
  githubToken: string // fine-grained or classic PAT; '' = anonymous
}

/**
 * FB-2: where secrets are kept, chosen by the user (default 'memory').
 * 'tab' = the tab's session storage (survives a reload, dies with the tab);
 * 'device' = this browser's local storage. Only the CHOICE lives in Preferences.
 */
export type SecretsPersistence = 'memory' | 'tab' | 'device'
export const SECRETS_PERSISTENCE_LEVELS: readonly SecretsPersistence[] = ['memory', 'tab', 'device']

// ── Batched classification (docs/batching.md) ────────────────────────
/** One request per issue, or every selected issue in as few requests as fit. */
export type ClassifyMode = 'batched' | 'per-issue'

/** Per-issue trimming profiles of a batched request, loosest → tightest. */
export type TrimmingProfileId = 'standard' | 'compact' | 'condensed' | 'tight' | 'minimal'

// ── Preferences (non-secret, persisted in localStorage) ──────────────
export interface Preferences {
  lastRepo: string // raw text of the last repo input
  lastAnalysisId: string | null // reopened after reload
  includeClosedByDefault: boolean
  fetchComments: 'auto' | 'always' | 'never' // auto = on when a token is present
  maxCommentsPerIssue: number // default 8
  maxIssuesToLoad: number // default 1000
  concurrency: number // default 4, clamp 1..8
  jevModel: string // default 'jev-latest'
  lowConfidenceThreshold: number // default 0.5
  classifyMode: ClassifyMode // default 'batched'; 'per-issue' is the fallback (docs/batching.md)
  trimmingFloor: TrimmingProfileId // tightest profile the batch fitter may use; default 'minimal'
  defaultExportOptions: ExportOptions // seed for new analyses' working state
  theme: 'system' | 'light' | 'dark' // §10.2, default 'system'
  onboarding: { keys: boolean; repo: boolean; classify: boolean } // first-run checklist, §10.1
  keysBannerDismissed: boolean // §2.1 step 2, Task 4: "Keys required" banner dismissal
  /** Ignored since 2026-09-24 (the card is no longer dismissible); kept only so old stored data still parses. */
  homeProviderCardDismissed: boolean
  /** Manual GPU/VRAM correction for the hardware-fit panel (docs/hardware-fit.md). Detected values are never persisted. */
  hardwareOverride?: HardwareOverride | null // default null
  provider: ProviderConfig // T16: TypeSafe cloud (default) or a local Jev-compatible server; never a key
  secretsPersistence: SecretsPersistence // FB-2: default 'memory'; the level only, never a secret
}

// ── Filters, sorting, export ─────────────────────────────────────────
/** Integer weights 0..100 (step 5). Not required to sum to 100; the formula normalizes. */
export interface PriorityWeights {
  criticality: number // default 40
  relevance: number // default 30
  complexity: number // default 15 (inverted: simpler → higher priority)
  effort: number // default 15 (inverted: less effort → higher priority)
}

export type SortKey =
  | 'priority'
  | 'criticality'
  | 'complexity'
  | 'effort'
  | 'relevance'
  | 'minConfidence'
  | 'createdAt'
  | 'updatedAt'
  | 'commentCount'
  | 'number'
export type SortDirection = 'asc' | 'desc'
export interface SortRule {
  key: SortKey
  direction: SortDirection
}
export type ExportOrder = SortRule[] // ordered, first rule has highest priority

export interface IssueFilter {
  complexity: Level[] // empty = no filter
  criticality: Level[]
  effort: Level[]
  kind: IssueKind[] // empty = no filter (Task 12, §6.3 Kind column)
  relevanceMin: number
  relevanceMax: number
  minConfidence: number
  statuses: ClassificationStatus[]
  labels: string[]
  text: string
}

/** `'text'` (default) is the plain-text report; `'markdown'`/`'html'` are the AI-feeding and
 * viewable/shareable exports (docs/export-format.md). */
export type ExportFormat = 'text' | 'markdown' | 'html'

export interface ExportOptions {
  order: ExportOrder
  /**
   * FB export: 'table' (default) makes the export use the *exact* table
   * pipeline for the current analysis (dismissal gated by
   * `working.showDismissed`, `filterRows(working.filter)` with no
   * unclassified bypass, `sortRowsBy(working.tableSort)`) — see
   * `domain/exportText.ts`'s `partitionForExport`. `scope`, `includeDismissed`
   * and `includeUnclassified` below are only consulted in `'custom'` mode.
   */
  orderMode: 'table' | 'custom'
  scope: 'all' | 'filtered'
  includeUnclassified: boolean
  includeDismissed: boolean
  includeConfidence: boolean
  includeUrls: boolean
  /** Output format: plain text (default), Markdown, or self-contained HTML. */
  format: ExportFormat
  /** HTML export only: adds a per-row `<details>` with the trimmed issue body. Default false. */
  includeBodies: boolean
}

// Only non-secret data has a storage key. There is deliberately no key for secrets.
export const STORAGE_PREFIX = 'local-issue-classifier:'
export const STORAGE_KEYS = {
  preferences: 'local-issue-classifier:preferences:v1',
  analysesIndex: 'local-issue-classifier:analyses:v1', // AnalysisSummary[]
  analysis: (id: string) => `local-issue-classifier:analysis:v1:${id}`, // one Analysis per key
} as const

// ── Factories ──────────────────────────────────────────────────────────
// Every defaultX() returns a fresh object (and fresh nested arrays/objects)
// on each call: mutating one result must never affect another.

export function defaultSecrets(): Secrets {
  return {
    jevApiKey: '',
    githubToken: '',
  }
}

/**
 * The default export order: Criticality desc → Relevance desc → Effort asc
 * (§2.6). Shared by defaultExportOptions() and defaultTableSort() — each
 * call below returns its own fresh array, never a shared reference.
 */
function defaultSortOrder(): ExportOrder {
  return [
    { key: 'criticality', direction: 'desc' },
    { key: 'relevance', direction: 'desc' },
    { key: 'effort', direction: 'asc' },
  ]
}

export function defaultTableSort(): ExportOrder {
  return defaultSortOrder()
}

export function defaultExportOptions(): ExportOptions {
  return {
    order: defaultSortOrder(),
    // FB export: mirror the table by default so the export can never show a
    // different row set/order than what the user is looking at (§2.6).
    orderMode: 'table',
    // "the current filtered view (default)", §2.6.
    scope: 'filtered',
    includeUnclassified: true,
    includeDismissed: false,
    includeConfidence: true,
    includeUrls: true,
    format: 'text',
    includeBodies: false,
  }
}

/**
 * Tolerant read of a possibly-older stored `ExportOptions` (same pattern as
 * `domain/columns.ts`'s `resolveVisibleColumns`): an analysis saved before
 * `orderMode`, `format` or `includeBodies` existed is missing those fields (or
 * `format` may hold an since-removed value), so each falls back to its default
 * rather than passing through `undefined`/unrecognized. Everything else is
 * passed through as-is.
 */
export function resolveExportOptions(stored: ExportOptions | undefined): ExportOptions {
  if (!stored) return defaultExportOptions()
  const orderMode = stored.orderMode === 'table' || stored.orderMode === 'custom' ? stored.orderMode : 'table'
  const format: ExportFormat =
    stored.format === 'markdown' || stored.format === 'html' || stored.format === 'text' ? stored.format : 'text'
  const includeBodies = typeof stored.includeBodies === 'boolean' ? stored.includeBodies : false
  return { ...stored, orderMode, format, includeBodies }
}

export function defaultPriorityWeights(): PriorityWeights {
  return {
    criticality: 40,
    relevance: 30,
    complexity: 15,
    effort: 15,
  }
}

export function defaultFilter(): IssueFilter {
  return {
    complexity: [],
    criticality: [],
    effort: [],
    kind: [],
    relevanceMin: 0,
    relevanceMax: 100,
    minConfidence: 0,
    statuses: [],
    labels: [],
    text: '',
  }
}

/** Deep-copies an ExportOptions value so a seeded working state never aliases it. */
function cloneExportOptions(options: ExportOptions): ExportOptions {
  return {
    order: options.order.map((rule) => ({ ...rule })),
    orderMode: options.orderMode,
    scope: options.scope,
    includeUnclassified: options.includeUnclassified,
    includeDismissed: options.includeDismissed,
    includeConfidence: options.includeConfidence,
    includeUrls: options.includeUrls,
    format: options.format,
    includeBodies: options.includeBodies,
  }
}

export function defaultPreferences(): Preferences {
  return {
    lastRepo: '',
    lastAnalysisId: null,
    includeClosedByDefault: false,
    fetchComments: 'auto',
    maxCommentsPerIssue: 8,
    maxIssuesToLoad: 1000,
    concurrency: 4,
    jevModel: DEFAULT_JEV_MODEL,
    lowConfidenceThreshold: 0.5,
    classifyMode: 'batched',
    trimmingFloor: 'minimal',
    defaultExportOptions: defaultExportOptions(),
    theme: 'system',
    onboarding: { keys: false, repo: false, classify: false },
    keysBannerDismissed: false,
    homeProviderCardDismissed: false,
    hardwareOverride: null,
    provider: defaultProviderConfig(),
    secretsPersistence: 'memory',
  }
}

export function defaultProjectContext(name: string): ProjectContext {
  return {
    name,
    description: null,
    topics: [],
    manifest: { source: null, name: null, description: null },
    readmeExcerpt: null,
    contributingExcerpt: null,
    docsIndex: [],
  }
}

/**
 * Working state for a new analysis. The export options are seeded from the
 * user's `prefs.defaultExportOptions` (§3 comment on Preferences); the
 * filter, table sort and priority weights start from their own defaults.
 */
export function defaultWorkingState(prefs: Preferences): AnalysisWorkingState {
  return {
    filter: defaultFilter(),
    tableSort: defaultTableSort(),
    exportOptions: cloneExportOptions(prefs.defaultExportOptions),
    priorityWeights: defaultPriorityWeights(),
    dismissed: [],
    showDismissed: false,
    expandedIssue: null,
    visibleColumns: [...DEFAULT_VISIBLE_COLUMNS],
  }
}

export interface DefaultAnalysisParams {
  id: string
  repo: Repo
  stateFilter: Analysis['stateFilter']
  now: string // ISO 8601, injected — domain code never reads the real clock
  prefs: Preferences
}

export function defaultAnalysis(params: DefaultAnalysisParams): Analysis {
  const { id, repo, stateFilter, now, prefs } = params
  return {
    schemaVersion: 1,
    id,
    name: `${repo.fullName} (${stateFilter})`,
    repo,
    stateFilter,
    createdAt: now,
    updatedAt: now,
    fetchedAt: now,
    commentsFetched: false,
    projectContext: defaultProjectContext(repo.fullName),
    rows: [],
    working: defaultWorkingState(prefs),
  }
}
