// Icon pipeline tests (SPEC §10.5): the normalizer, the generator, and a sanity
// scan over every committed generated icon.
import { describe, expect, it } from 'vitest'
import { mkdtempSync, readFileSync, readdirSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import {
  buildIcons,
  componentName,
  normalizeSvg,
  renderIconComponent,
} from '../scripts/build-icons.mjs'

const ROOT = join(__dirname, '..')
const ICONS_DIR = join(ROOT, 'src', 'assets', 'icons')

describe('componentName', () => {
  it('turns a kebab-case file name into Icon<PascalCase>', () => {
    expect(componentName('chevron-down.svg')).toBe('IconChevronDown')
    expect(componentName('signal-3.svg')).toBe('IconSignal3')
    expect(componentName('eye.svg')).toBe('IconEye')
  })
})

describe('normalizeSvg', () => {
  const dirty = `<?xml version="1.0"?>
<!-- exported by some editor -->
<svg xmlns="http://www.w3.org/2000/svg" id="root" width="16" height="16" onload="alert(1)">
  <metadata>junk</metadata><title>Old title</title>
  <script>alert(1)</script>
  <path id="p1" class="c" style="fill:red" fill="#FF0000" onclick="x()" d="M0 0h1v1H0z"/>
  <path fill="#000" fill-opacity=".3" stroke="#123456" d="M1 1h1v1H1z"/>
  <a href="javascript:alert(1)"><path d="M2 2h1v1H2z"/></a>
</svg>`

  it('derives a viewBox from width/height when it is missing', () => {
    expect(normalizeSvg(dirty).viewBox).toBe('0 0 16 16')
  })

  it('keeps an explicit viewBox', () => {
    const svg = '<svg viewBox="0 0 32 32"><path d="M0 0h1v1H0z"/></svg>'
    expect(normalizeSvg(svg).viewBox).toBe('0 0 32 32')
  })

  it('strips scripts, event handlers, links, metadata, ids, classes and styles', () => {
    const { inner } = normalizeSvg(dirty)
    expect(inner).not.toMatch(/<script|alert|onclick|onload|href|metadata|<title|id=|class=|style=/)
    expect(inner).not.toMatch(/<\/?a[\s>]/)
  })

  it('recolors fills and strokes to currentColor and keeps tonal opacity', () => {
    const { inner } = normalizeSvg(dirty)
    expect(inner).not.toMatch(/#[0-9a-f]{3,6}/i)
    expect(inner).toContain('fill-opacity=".3"')
    expect(inner).toContain('stroke="currentColor"')
  })

  it('refuses a file with neither a viewBox nor a numeric size', () => {
    expect(() => normalizeSvg('<svg><path d="M0 0z"/></svg>')).toThrow(/viewBox/)
  })
})

describe('renderIconComponent', () => {
  it('renders a decorative, crisp, currentColor SVG sized to its grid', () => {
    const sfc = renderIconComponent({
      source: 'design/icons/custom/x.svg',
      viewBox: '0 0 16 16',
      inner: '<path d="M0 0h1v1H0z"/>',
    })
    expect(sfc).toContain('Generated by scripts/build-icons.mjs from design/icons/custom/x.svg')
    expect(sfc).toMatch(/<template>\s*<svg /)
    for (const attr of [
      'viewBox="0 0 16 16"',
      'width="16"',
      'height="16"',
      'fill="currentColor"',
      'shape-rendering="crispEdges"',
      'aria-hidden="true"',
      'focusable="false"',
    ]) {
      expect(sfc).toContain(attr)
    }
  })
})

describe('renderIconComponent (stroke mode)', () => {
  it('renders a 1.5-stroke, round-capped, anti-aliased icon at 16 px from a 24 grid', () => {
    const sfc = renderIconComponent({
      source: 'design/icons/stroke/x.svg',
      viewBox: '0 0 24 24',
      inner: '<path d="M6 6l12 12"/>',
      mode: 'stroke',
    })
    for (const attr of [
      'viewBox="0 0 24 24"',
      'width="16"',
      'height="16"',
      'fill="none"',
      'stroke="currentColor"',
      'stroke-width="1.5"',
      'stroke-linecap="round"',
      'stroke-linejoin="round"',
      'shape-rendering="geometricPrecision"',
      'aria-hidden="true"',
      'focusable="false"',
    ]) {
      expect(sfc).toContain(attr)
    }
    expect(sfc).not.toContain('crispEdges')
  })
})

describe('buildIcons', () => {
  it('regenerates exactly the committed icons (run `pnpm icons` if this fails)', () => {
    const out = mkdtempSync(join(tmpdir(), 'ic-icons-'))
    try {
      const written = buildIcons({ rootDir: ROOT, outDir: out })
      expect(written.length).toBeGreaterThan(0)
      const committed = readdirSync(ICONS_DIR).filter((f) => f !== '.gitkeep').sort()
      expect(readdirSync(out).sort()).toEqual(committed)
      for (const file of committed) {
        expect(readFileSync(join(out, file), 'utf8'), file).toBe(
          readFileSync(join(ICONS_DIR, file), 'utf8'),
        )
      }
    } finally {
      rmSync(out, { recursive: true, force: true })
    }
  })
})

describe('generated icons (sanity)', () => {
  const files = readdirSync(ICONS_DIR).filter((f) => f.endsWith('.vue'))

  it('exist, including the logo, the empty-state art and the UI set', () => {
    for (const name of [
      'IconLogo',
      'IconEye',
      'IconEyeOff',
      'IconClose',
      'IconChevronDown',
      'IconEmptyBox',
    ]) {
      expect(files).toContain(`${name}.vue`)
    }
  })

  it('draws every UI icon as a 24-grid stroke icon; pixel art is only the logo and empty-state art', () => {
    const pixel = files.filter((f) => readFileSync(join(ICONS_DIR, f), 'utf8').includes('crispEdges'))
    expect(pixel.sort()).toEqual(['IconEmptyBox.vue', 'IconLogo.vue'])
    for (const name of ['IconColumns', 'IconArrowLeft', 'IconLock', 'IconSearch', 'IconSettings']) {
      const source = readFileSync(join(ICONS_DIR, `${name}.vue`), 'utf8')
      expect(source, name).toContain('viewBox="0 0 24 24"')
      expect(source, name).toContain('stroke-width="1.5"')
    }
  })

  it.each(files)('%s uses currentColor, has a viewBox and nothing executable', (file) => {
    const source = readFileSync(join(ICONS_DIR, file), 'utf8')
    expect(source).toContain('currentColor')
    expect(source).toMatch(/viewBox="0 0 \d+ \d+"/)
    expect(source).not.toMatch(/<script/i)
    expect(source).not.toMatch(/\son[a-z]+\s*=/i)
    expect(source).not.toMatch(/href\s*=/i)
  })
})
