// Social link-preview (GitHub issue #3, docs/architecture.md "Link preview"). Exercises the
// meta tags a chat/social client reads to render a rich card for https://issueclassifier.com,
// the committed public/og-image.png (generated by `pnpm og-image`, scripts/build-og-image.mjs)
// and the pure helpers that build it. No image-processing dependency is added: PNG dimensions
// are read straight from the IHDR chunk via the existing dependency-free
// scripts/build-favicon-png.mjs reader, same as tests/favicon.test.ts.
import { describe, expect, it } from 'vitest'
import { readFileSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { readPngSize } from '../scripts/build-favicon-png.mjs'
import {
  HEIGHT,
  WIDTH,
  buildPage,
  embedFonts,
  findBrowserPath,
  toFileUrl,
  wrapHtml,
} from '../scripts/build-og-image.mjs'
import { REQUIRED_DIST_FILES } from '../scripts/build-check.mjs'

const ROOT = join(__dirname, '..')
const html = readFileSync(join(ROOT, 'index.html'), 'utf8')

/** Pulls one meta tag's `content` by its `property` or `name` attribute. */
function metaContent(source: string, attr: 'property' | 'name', key: string): string | undefined {
  const re = new RegExp(`<meta\\s+${attr}="${key}"\\s+content="([^"]*)"`)
  return re.exec(source)?.[1]
}

describe('index.html link preview meta tags', () => {
  it('has a short, descriptive <title> distinct from the PWA app name', () => {
    const title = /<title>([^<]+)<\/title>/.exec(html)?.[1]
    expect(title).toBe('Issue Classifier — AI triage for GitHub issues')
    expect(title!.length).toBeLessThanOrEqual(60)
  })

  it('has a <meta name="description">', () => {
    const description = metaContent(html, 'name', 'description')
    expect(description).toBeTruthy()
    expect(description!.length).toBeGreaterThan(20)
    expect(description!.length).toBeLessThanOrEqual(200)
  })

  it('has Open Graph tags describing the site', () => {
    expect(metaContent(html, 'property', 'og:type')).toBe('website')
    expect(metaContent(html, 'property', 'og:site_name')).toBe('Issue Classifier')
    expect(metaContent(html, 'property', 'og:url')).toBe('https://issueclassifier.com/')
    expect(metaContent(html, 'property', 'og:title')).toBe(
      metaContent(html, 'name', 'description') && /<title>([^<]+)<\/title>/.exec(html)?.[1],
    )
  })

  it('og:description matches the meta description', () => {
    expect(metaContent(html, 'property', 'og:description')).toBe(
      metaContent(html, 'name', 'description'),
    )
  })

  it('og:image is absolute https on issueclassifier.com with 1200x630 dimensions declared', () => {
    const image = metaContent(html, 'property', 'og:image')
    expect(image).toBe('https://issueclassifier.com/og-image.png')
    expect(metaContent(html, 'property', 'og:image:width')).toBe('1200')
    expect(metaContent(html, 'property', 'og:image:height')).toBe('630')
    expect(metaContent(html, 'property', 'og:image:type')).toBe('image/png')
    expect(metaContent(html, 'property', 'og:image:alt')).toBeTruthy()
  })

  it('has a Twitter Card that mirrors the Open Graph title, description and image', () => {
    expect(metaContent(html, 'name', 'twitter:card')).toBe('summary_large_image')
    expect(metaContent(html, 'name', 'twitter:title')).toBe(metaContent(html, 'property', 'og:title'))
    expect(metaContent(html, 'name', 'twitter:description')).toBe(
      metaContent(html, 'property', 'og:description'),
    )
    expect(metaContent(html, 'name', 'twitter:image')).toBe(metaContent(html, 'property', 'og:image'))
    expect(metaContent(html, 'name', 'twitter:image:alt')).toBe(
      metaContent(html, 'property', 'og:image:alt'),
    )
  })

  it('keeps the Content-Security-Policy meta tag untouched', () => {
    expect(html).toContain("default-src 'self'")
    expect(html).toContain("img-src 'self' data: https://avatars.githubusercontent.com")
  })
})

describe('public/og-image.png (committed output — run `pnpm og-image` if this fails)', () => {
  const OG_IMAGE_PATH = join(ROOT, 'public', 'og-image.png')

  it('exists and is exactly 1200x630', () => {
    const png = readFileSync(OG_IMAGE_PATH)
    expect(readPngSize(png)).toEqual({ width: 1200, height: 630 })
  })

  it('stays under the size budget (< 300 KB)', () => {
    const bytes = statSync(OG_IMAGE_PATH).size
    expect(bytes).toBeLessThan(300 * 1024)
  })
})

describe('dist/ build requirements', () => {
  it('requires og-image.png to ship in the Cloudflare Pages build output', () => {
    expect(REQUIRED_DIST_FILES).toContain('og-image.png')
  })
})

describe('scripts/build-og-image.mjs helpers', () => {
  it('embeds font data URIs into the fonts style marker', () => {
    const source = '<svg><style id="fonts"></style><text>hi</text></svg>'
    const out = embedFonts(source, { sansDataUri: 'data:font/woff2;base64,AAA', monoDataUri: 'data:font/woff2;base64,BBB' })
    expect(out).toContain("url(\"data:font/woff2;base64,AAA\")")
    expect(out).toContain("url(\"data:font/woff2;base64,BBB\")")
    expect(out).toContain("font-family: 'Geist Variable'")
    expect(out).toContain("font-family: 'Geist Mono Variable'")
  })

  it('throws when the source is missing the fonts marker', () => {
    expect(() => embedFonts('<svg></svg>', { sansDataUri: 'x', monoDataUri: 'y' })).toThrow(/fonts/)
  })

  it('wraps SVG markup in a page pinned to the exact WIDTHxHEIGHT', () => {
    const out = wrapHtml('<svg></svg>')
    expect(out).toContain(`width:${WIDTH}px;height:${HEIGHT}px`)
    expect(out).toContain('<svg></svg>')
  })

  it('converts an absolute path to a well-formed file:// URL on both path styles', () => {
    expect(toFileUrl('C:\\repo\\design\\og\\og-image.svg')).toBe('file:///C:/repo/design/og/og-image.svg')
    expect(toFileUrl('/repo/design/og/og-image.svg')).toBe('file:///repo/design/og/og-image.svg')
  })

  it('picks the first candidate the injected existsFn reports as present', () => {
    const exists = (p: string) => p === '/usr/bin/chromium'
    expect(findBrowserPath(['/usr/bin/google-chrome', '/usr/bin/chromium'], exists)).toBe(
      '/usr/bin/chromium',
    )
    expect(findBrowserPath(['/nope'], exists)).toBeUndefined()
  })

  it('builds the final page from the committed SVG source with fonts embedded (no external URLs)', () => {
    const page = buildPage({ rootDir: ROOT })
    expect(page).toContain('@font-face')
    expect(page).toContain('data:font/woff2;base64,')
    // No fetched resource (font src, stylesheet, script, image) points off-machine. The SVG's
    // own xmlns declaration is a namespace URI, not a network request, so it is exempt.
    expect(page).not.toMatch(/\b(?:src|href)\s*=\s*"https?:\/\//)
    expect(page).not.toMatch(/url\(\s*"?https?:\/\//)
  })
})
