// public/_headers — the production security/cache headers for the Cloudflare
// Pages deployment (docs/architecture.md "Deployment modes"). Vite's default
// publicDir behaviour copies every file under public/ into dist/ unchanged, so
// there is no custom plugin to unit test for the copy step itself; `pnpm
// build:check` (tests/buildCheck.test.ts, scripts/build-check.mjs) is the
// integration check that a real `pnpm build` actually produces dist/_headers.
//
// Cloudflare Pages does NOT apply `_headers` to responses generated by a Pages
// Function (verified against the platform docs, 2026-09-24): a request under
// /jev/* is served entirely by functions/jev/[[path]].ts, which already sets
// its own Cache-Control: no-store and X-Content-Type-Options (server/jevProxyPolicy.ts
// JEV_RESPONSE_HEADERS). A `/jev/*` block here would therefore be silently
// ineffective, so this file deliberately has none, and the block below only
// covers the two hashed/near-static asset trees this app actually serves.
import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = join(__dirname, '..')
const HEADERS = readFileSync(join(ROOT, 'public', '_headers'), 'utf8')
const HTML = readFileSync(join(ROOT, 'index.html'), 'utf8')

interface HeaderBlock {
  pattern: string
  headers: Record<string, string>
}

/** Parses the Cloudflare Pages `_headers` format: a path pattern line, then indented `Name: value` lines. */
function parseHeadersFile(text: string): HeaderBlock[] {
  const blocks: HeaderBlock[] = []
  let current: HeaderBlock | null = null
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.replace(/\s+$/, '')
    if (line.trim() === '' || line.trim().startsWith('#')) continue
    if (/^\s/.test(line)) {
      if (!current) throw new Error(`Header line outside of any block: "${line}"`)
      const sep = line.indexOf(':')
      if (sep === -1) throw new Error(`Malformed header line: "${line}"`)
      current.headers[line.slice(0, sep).trim()] = line.slice(sep + 1).trim()
    } else {
      current = { pattern: line.trim(), headers: {} }
      blocks.push(current)
    }
  }
  return blocks
}

const blocks = parseHeadersFile(HEADERS)
const blockFor = (pattern: string) => blocks.find((b) => b.pattern === pattern)

const metaCsp = /http-equiv="Content-Security-Policy"\s+content="([^"]+)"/.exec(HTML)?.[1] ?? ''

describe('public/_headers', () => {
  it('has exactly the blocks this app needs, in a stable, non-conflicting set', () => {
    expect(blocks.map((b) => b.pattern)).toEqual([
      '/*',
      '/assets/*',
      '/ort/*',
      'https://:project.pages.dev/*',
      'https://:version.:project.pages.dev/*',
    ])
  })

  it('mirrors the index.html Content-Security-Policy meta tag exactly on /*', () => {
    expect(metaCsp.length).toBeGreaterThan(0)
    expect(blockFor('/*')?.headers['Content-Security-Policy']).toBe(metaCsp)
  })

  it('sets the baseline security headers on every response', () => {
    const headers = blockFor('/*')?.headers ?? {}
    expect(headers['X-Content-Type-Options']).toBe('nosniff')
    expect(headers['Referrer-Policy']).toBe('strict-origin-when-cross-origin')
    expect(headers['Cross-Origin-Opener-Policy']).toBe('same-origin')
  })

  it('denies camera, microphone and geolocation via Permissions-Policy', () => {
    const policy = blockFor('/*')?.headers['Permissions-Policy'] ?? ''
    for (const feature of ['camera', 'microphone', 'geolocation']) {
      expect(policy).toMatch(new RegExp(`${feature}=\\(\\)`))
    }
  })

  it('does not set Cache-Control on /*, so the two asset blocks below never comma-merge with a default', () => {
    expect(blockFor('/*')?.headers['Cache-Control']).toBeUndefined()
  })

  it.each(['/assets/*', '/ort/*'])('caches %s long-term and immutably (hashed/rarely-changing build assets)', (pattern) => {
    const cacheControl = blockFor(pattern)?.headers['Cache-Control'] ?? ''
    expect(cacheControl).toContain('immutable')
    const maxAge = /max-age=(\d+)/.exec(cacheControl)?.[1]
    expect(Number(maxAge)).toBeGreaterThanOrEqual(31536000) // >= 1 year
  })

  it('has no rule for /jev/*: the Pages Function there sets its own headers directly', () => {
    expect(blockFor('/jev/*')).toBeUndefined()
  })

  // GitHub issue #8 (docs/architecture.md "SEO"): the *.pages.dev domain (the project's
  // permanent alias) and its per-branch/per-deployment preview subdomains must never be
  // indexed separately from https://issueclassifier.com — the placeholder syntax below is
  // Cloudflare's own documented example (developers.cloudflare.com/pages/configuration/headers/
  // "Search Engine Indexing Control"), not this project's literal name.
  it.each(['https://:project.pages.dev/*', 'https://:version.:project.pages.dev/*'])(
    'sets X-Robots-Tag: noindex on %s',
    (pattern) => {
      expect(blockFor(pattern)?.headers['X-Robots-Tag']).toBe('noindex')
    },
  )

  it('adds the two pages.dev noindex rules without touching the CSP mirrored on /*', () => {
    expect(metaCsp.length).toBeGreaterThan(0)
    expect(blockFor('/*')?.headers['Content-Security-Policy']).toBe(metaCsp)
    expect(blockFor('https://:project.pages.dev/*')?.headers['Content-Security-Policy']).toBeUndefined()
  })
})
