<!-- Generated by scripts/build-icons.mjs from design/icons/custom/trash.svg. Do not edit; run `pnpm icons`. -->
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" fill="currentColor" shape-rendering="crispEdges" aria-hidden="true" focusable="false"><path d="M6 1h4v1h-4zM1 2h14v1h-14zM1 3h14v1h-14zM2 5h12v1h-12zM2 6h2v1h-2zM6 6h1v1h-1zM9 6h1v1h-1zM12 6h2v1h-2zM2 7h2v1h-2zM6 7h1v1h-1zM9 7h1v1h-1zM12 7h2v1h-2zM2 8h2v1h-2zM6 8h1v1h-1zM9 8h1v1h-1zM12 8h2v1h-2zM2 9h2v1h-2zM6 9h1v1h-1zM9 9h1v1h-1zM12 9h2v1h-2zM2 10h2v1h-2zM6 10h1v1h-1zM9 10h1v1h-1zM12 10h2v1h-2zM2 11h2v1h-2zM6 11h1v1h-1zM9 11h1v1h-1zM12 11h2v1h-2zM2 12h2v1h-2zM6 12h1v1h-1zM9 12h1v1h-1zM12 12h2v1h-2zM2 13h2v1h-2zM12 13h2v1h-2zM3 14h10v1h-10z"/></svg>
</template>
