<!-- Generated by scripts/build-icons.mjs from design/icons/custom/repo.svg. Do not edit; run `pnpm icons`. -->
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" fill="currentColor" shape-rendering="crispEdges" aria-hidden="true" focusable="false"><path d="M2 1h11v1h-11zM2 2h1v1h-1zM12 2h2v1h-2zM2 3h1v1h-1zM4 3h2v1h-2zM12 3h2v1h-2zM2 4h1v1h-1zM4 4h2v1h-2zM12 4h2v1h-2zM2 5h1v1h-1zM4 5h2v1h-2zM12 5h2v1h-2zM2 6h1v1h-1zM4 6h2v1h-2zM12 6h2v1h-2zM2 7h1v1h-1zM4 7h2v1h-2zM12 7h2v1h-2zM2 8h1v1h-1zM4 8h2v1h-2zM12 8h2v1h-2zM2 9h1v1h-1zM12 9h2v1h-2zM2 10h12v1h-12zM2 11h1v1h-1zM14 11h1v1h-1zM2 12h1v1h-1zM4 12h2v1h-2zM7 12h8v1h-8zM2 13h1v1h-1zM4 13h2v1h-2zM2 14h3v1h-3zM6 14h1v1h-1z"/></svg>
</template>
