<!-- Generated by scripts/build-icons.mjs from design/icons/stroke/columns.svg. Do not edit; run `pnpm icons`. -->
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" shape-rendering="geometricPrecision" aria-hidden="true" focusable="false"><rect x="4" y="4.5" width="16" height="15" rx="1.5"/><path d="M9.5 4.5v15M14.5 4.5v15"/></svg>
</template>
