<!-- Generated by scripts/build-icons.mjs from design/icons/custom/eye-off.svg. Do not edit; run `pnpm icons`. -->
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" fill="currentColor" shape-rendering="crispEdges" aria-hidden="true" focusable="false"><path d="M1 1h2v1h-2zM2 2h2v1h-2zM3 3h2v1h-2zM6 3h5v1h-5zM4 4h2v1h-2zM11 4h2v1h-2zM2 5h1v1h-1zM5 5h2v1h-2zM13 5h1v1h-1zM1 6h1v1h-1zM6 6h2v1h-2zM14 6h1v1h-1zM0 7h1v1h-1zM7 7h2v1h-2zM15 7h1v1h-1zM0 8h1v1h-1zM8 8h2v1h-2zM15 8h1v1h-1zM1 9h1v1h-1zM9 9h2v1h-2zM14 9h1v1h-1zM2 10h1v1h-1zM10 10h2v1h-2zM13 10h1v1h-1zM3 11h2v1h-2zM11 11h2v1h-2zM5 12h6v1h-6zM12 12h2v1h-2zM13 13h2v1h-2zM14 14h2v1h-2z"/></svg>
</template>
