<!-- Generated by scripts/build-icons.mjs from design/icons/custom/warning.svg. Do not edit; run `pnpm icons`. -->
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" fill="currentColor" shape-rendering="crispEdges" aria-hidden="true" focusable="false"><path d="M7 1h2v1h-2zM6 2h4v1h-4zM6 3h1v1h-1zM9 3h1v1h-1zM5 4h2v1h-2zM9 4h2v1h-2zM5 5h1v1h-1zM7 5h2v1h-2zM10 5h1v1h-1zM4 6h2v1h-2zM7 6h2v1h-2zM10 6h2v1h-2zM4 7h1v1h-1zM7 7h2v1h-2zM11 7h1v1h-1zM3 8h2v1h-2zM7 8h2v1h-2zM11 8h2v1h-2zM3 9h1v1h-1zM12 9h1v1h-1zM2 10h2v1h-2zM7 10h2v1h-2zM12 10h2v1h-2zM2 11h1v1h-1zM7 11h2v1h-2zM13 11h1v1h-1zM1 12h2v1h-2zM13 12h2v1h-2zM1 13h1v1h-1zM14 13h1v1h-1zM1 14h14v1h-14z"/></svg>
</template>
