<!-- Generated by scripts/build-icons.mjs from design/icons/pixel/signal-1.svg. Do not edit; run `pnpm icons`. -->
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" fill="currentColor" shape-rendering="crispEdges" aria-hidden="true" focusable="false"><path d="M2 10h3v1h-3zM2 11h3v1h-3zM2 12h3v1h-3zM2 13h3v1h-3z"/><path fill-opacity=".3" d="M10 2h3v1h-3zM10 3h3v1h-3zM10 4h3v1h-3zM10 5h3v1h-3zM6 6h3v1h-3zM10 6h3v1h-3zM6 7h3v1h-3zM10 7h3v1h-3zM6 8h3v1h-3zM10 8h3v1h-3zM6 9h3v1h-3zM10 9h3v1h-3zM6 10h3v1h-3zM10 10h3v1h-3zM6 11h3v1h-3zM10 11h3v1h-3zM6 12h3v1h-3zM10 12h3v1h-3zM6 13h3v1h-3zM10 13h3v1h-3z"/></svg>
</template>
