<!-- Generated by scripts/build-icons.mjs from design/icons/stroke/copy.svg. Do not edit; run `pnpm icons`. -->
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" shape-rendering="geometricPrecision" aria-hidden="true" focusable="false"><rect x="4.5" y="4.5" width="11" height="11" rx="2"/><rect x="8.5" y="8.5" width="11" height="11" rx="2"/></svg>
</template>
