<!-- Generated by scripts/build-icons.mjs from design/icons/stroke/coffee.svg. Do not edit; run `pnpm icons`. -->
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" shape-rendering="geometricPrecision" aria-hidden="true" focusable="false"><rect x="4" y="9" width="12" height="11" rx="2"/><path d="M16 11h1a3 3 0 0 1 0 6h-1"/><path d="M9 7c0-1 1.5-1 1.5-2S9 4 9 3M13 7c0-1 1.5-1 1.5-2S13 4 13 3"/></svg>
</template>
