<!-- Generated by scripts/build-icons.mjs from design/icons/custom/external-link.svg. Do not edit; run `pnpm icons`. -->
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" fill="currentColor" shape-rendering="crispEdges" aria-hidden="true" focusable="false"><path d="M9 1h6v1h-6zM12 2h3v1h-3zM1 3h6v1h-6zM11 3h4v1h-4zM1 4h1v1h-1zM10 4h2v1h-2zM13 4h2v1h-2zM1 5h1v1h-1zM9 5h2v1h-2zM14 5h1v1h-1zM1 6h1v1h-1zM8 6h2v1h-2zM14 6h1v1h-1zM1 7h1v1h-1zM7 7h2v1h-2zM1 8h1v1h-1zM6 8h2v1h-2zM1 9h1v1h-1zM12 9h1v1h-1zM1 10h1v1h-1zM12 10h1v1h-1zM1 11h1v1h-1zM12 11h1v1h-1zM1 12h1v1h-1zM12 12h1v1h-1zM1 13h1v1h-1zM12 13h1v1h-1zM1 14h12v1h-12z"/></svg>
</template>
