<!-- Generated by scripts/build-icons.mjs from design/icons/custom/sun.svg. Do not edit; run `pnpm icons`. -->
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" fill="currentColor" shape-rendering="crispEdges" aria-hidden="true" focusable="false"><path d="M7 0h2v1h-2zM7 1h2v1h-2zM2 2h2v1h-2zM7 2h2v1h-2zM12 2h2v1h-2zM2 3h2v1h-2zM12 3h2v1h-2zM6 5h4v1h-4zM5 6h6v1h-6zM0 7h3v1h-3zM5 7h6v1h-6zM13 7h3v1h-3zM0 8h3v1h-3zM5 8h6v1h-6zM13 8h3v1h-3zM5 9h6v1h-6zM6 10h4v1h-4zM2 12h2v1h-2zM12 12h2v1h-2zM2 13h2v1h-2zM7 13h2v1h-2zM12 13h2v1h-2zM7 14h2v1h-2zM7 15h2v1h-2z"/></svg>
</template>
