<!-- Generated by scripts/build-icons.mjs from design/icons/custom/key.svg. Do not edit; run `pnpm icons`. -->
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" fill="currentColor" shape-rendering="crispEdges" aria-hidden="true" focusable="false"><path d="M2 5h4v1h-4zM1 6h2v1h-2zM5 6h2v1h-2zM0 7h2v1h-2zM6 7h10v1h-10zM0 8h2v1h-2zM6 8h10v1h-10zM1 9h2v1h-2zM5 9h2v1h-2zM12 9h1v1h-1zM14 9h2v1h-2zM2 10h4v1h-4zM12 10h1v1h-1zM14 10h2v1h-2z"/></svg>
</template>
