<!-- Generated by scripts/build-icons.mjs from design/icons/stroke/repo.svg. Do not edit; run `pnpm icons`. -->
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" shape-rendering="geometricPrecision" aria-hidden="true" focusable="false"><path d="M5 18.5v-13a1 1 0 0 1 1-1h12.5v12H7a2 2 0 0 0-2 2 2 2 0 0 0 2 2h11.5M9 8.5h5.5"/></svg>
</template>
