<!-- Generated by scripts/build-icons.mjs from design/icons/custom/moon.svg. Do not edit; run `pnpm icons`. -->
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" fill="currentColor" shape-rendering="crispEdges" aria-hidden="true" focusable="false"><path d="M5 1h4v1h-4zM3 2h3v1h-3zM2 3h3v1h-3zM1 4h3v1h-3zM1 5h3v1h-3zM0 6h3v1h-3zM0 7h3v1h-3zM0 8h3v1h-3zM0 9h3v1h-3zM15 9h1v1h-1zM1 10h3v1h-3zM14 10h2v1h-2zM1 11h4v1h-4zM13 11h3v1h-3zM2 12h6v1h-6zM10 12h5v1h-5zM3 13h11v1h-11zM5 14h6v1h-6z"/></svg>
</template>
