<!-- Generated by scripts/build-icons.mjs from design/icons/stroke/chevron-down.svg. Do not edit; run `pnpm icons`. -->
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" shape-rendering="geometricPrecision" aria-hidden="true" focusable="false"><path d="M6 9l6 6 6-6"/></svg>
</template>
