<!-- Generated by scripts/build-icons.mjs from design/icons/custom/search.svg. Do not edit; run `pnpm icons`. -->
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" fill="currentColor" shape-rendering="crispEdges" aria-hidden="true" focusable="false"><path d="M4 1h6v1h-6zM3 2h2v1h-2zM9 2h2v1h-2zM2 3h2v1h-2zM10 3h2v1h-2zM2 4h1v1h-1zM11 4h1v1h-1zM2 5h1v1h-1zM11 5h1v1h-1zM2 6h1v1h-1zM11 6h1v1h-1zM2 7h1v1h-1zM11 7h1v1h-1zM2 8h2v1h-2zM10 8h2v1h-2zM3 9h2v1h-2zM9 9h3v1h-3zM4 10h7v1h-7zM10 11h3v1h-3zM11 12h3v1h-3zM12 13h3v1h-3zM13 14h2v1h-2z"/></svg>
</template>
