// Ko-fi "Support the author" app-bar icon (2026-09-24). Unlike GitHubMarkIcon.vue
// and LinkedInMarkIcon.vue (which hand-inline a third party's real brand mark),
// this renders an **original** coffee-mug icon drawn for this project, because
// Ko-fi offers no monochrome variant to recolor and its Terms broadly restrict
// trademark use and modification (see THIRD_PARTY_NOTICES.md "Ko-fi support
// link" and docs/design.md "Icons" for the full sourcing note). It is generated
// by the normal scripts/build-icons.mjs stroke pipeline from
// design/icons/stroke/coffee.svg, then wrapped here the same way the other two
// app-bar marks are, so App.vue can treat all three social links identically.
import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { mount } from '@vue/test-utils'
import KofiMarkIcon from './KofiMarkIcon.vue'

const SOURCE = readFileSync(join(__dirname, 'KofiMarkIcon.vue'), 'utf8')
const GENERATED_SOURCE = readFileSync(join(__dirname, '..', 'assets', 'icons', 'IconCoffee.vue'), 'utf8')

describe('KofiMarkIcon', () => {
  it('renders an original 24-grid stroke icon (a coffee mug), not a hand-inlined brand mark', () => {
    const wrapper = mount(KofiMarkIcon)
    const svg = wrapper.get('svg')
    expect(svg.attributes('viewBox')).toBe('0 0 24 24')
    expect(svg.attributes('aria-hidden')).toBe('true')
    expect(svg.attributes('focusable')).toBe('false')
    // Stroke mode: fill="none", painted by the shared currentColor stroke —
    // distinct from GitHub's fill="currentColor" glyph and LinkedIn's fixed
    // brand-token fill, and proof this is not Ko-fi's own filled cup logo.
    expect(svg.attributes('fill')).toBe('none')
    expect(svg.attributes('stroke')).toBe('currentColor')
  })

  it('draws a mug body, a handle and steam, generated through the shared icon pipeline', () => {
    const wrapper = mount(KofiMarkIcon)
    const svg = wrapper.get('svg')
    expect(svg.find('rect').exists()).toBe(true)
    expect(svg.findAll('path').length).toBeGreaterThanOrEqual(2)
    expect(GENERATED_SOURCE).toContain('Generated by scripts/build-icons.mjs from design/icons/stroke/coffee.svg')
    expect(SOURCE).toContain("import IconCoffee from '../assets/icons/IconCoffee.vue'")
  })

  it('never hardcodes a color: no raw hex, and no Ko-fi brand color, anywhere in the rendered markup', () => {
    const wrapper = mount(KofiMarkIcon)
    expect(wrapper.html()).not.toMatch(/#[0-9a-fA-F]{3,8}\b/)
  })
})
