#!/usr/bin/env node
// Icon pipeline (design v2): design/icons/{stroke,pixel}/*.svg →
// one Vue SFC per icon in src/assets/icons/Icon<Name>.vue, plus an index of
// named re-exports. `stroke` icons are 24-grid line icons rendered at 16 px
// with a 1.5 stroke; `pixel` art (logo, empty-state art) keeps crisp edges.
// Each icon is imported explicitly where used, so unused
// icons are tree-shaken. Run with `pnpm icons`; the output is committed.
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

export const SOURCE_DIRS = [
  { dir: 'design/icons/stroke', mode: 'stroke' },
  { dir: 'design/icons/pixel', mode: 'pixel' },
]
/** Default rendered size of a stroke icon (the `--icon-sm` token). */
const STROKE_SIZE = 16
export const OUT_DIR = 'src/assets/icons'

/** Elements removed together with their content. */
const DROP_ELEMENTS = ['script', 'style', 'metadata', 'title', 'desc', 'foreignObject']
/** Elements replaced by their children (no links inside icons). */
const UNWRAP_ELEMENTS = ['a']

export function componentName(fileName) {
  const stem = fileName.replace(/\.svg$/i, '')
  const pascal = stem
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('')
  return `Icon${pascal}`
}

function parseAttributes(raw) {
  const attrs = []
  const re = /([^\s=/]+)\s*=\s*("([^"]*)"|'([^']*)')/g
  let m
  while ((m = re.exec(raw))) attrs.push([m[1], m[3] ?? m[4]])
  return attrs
}

function cleanAttributes(attrs) {
  const kept = []
  for (const [name, value] of attrs) {
    const lower = name.toLowerCase()
    if (/^on/.test(lower)) continue
    if (['id', 'class', 'style'].includes(lower)) continue
    if (lower === 'href' || lower.endsWith(':href')) continue
    if (lower.startsWith('xmlns') || lower.startsWith('xml:') || lower.startsWith('data-')) continue
    if (lower === 'fill') {
      // Children inherit currentColor from the root; only an explicit "none" survives.
      if (value.trim() === 'none') kept.push([name, 'none'])
      continue
    }
    if (lower === 'stroke') {
      kept.push([name, value.trim() === 'none' ? 'none' : 'currentColor'])
      continue
    }
    kept.push([name, value])
  }
  return kept
}

const serialize = (attrs) => attrs.map(([n, v]) => ` ${n}="${v}"`).join('')

/**
 * Normalizes one SVG source: enforces a viewBox, recolors to currentColor and
 * strips metadata, IDs, styles, links, scripts and event handlers.
 */
export function normalizeSvg(source) {
  let svg = source
    .replace(/<\?xml[\s\S]*?\?>/g, '')
    .replace(/<!DOCTYPE[\s\S]*?>/gi, '')
    .replace(/<!--[\s\S]*?-->/g, '')
  for (const el of DROP_ELEMENTS) {
    svg = svg
      .replace(new RegExp(`<${el}\\b[^>]*/>`, 'gi'), '')
      .replace(new RegExp(`<${el}\\b[\\s\\S]*?</${el}>`, 'gi'), '')
  }

  const open = /<svg\b([^>]*)>/i.exec(svg)
  const close = svg.lastIndexOf('</svg>')
  if (!open || close < 0) throw new Error('Not an <svg> document')
  const rootAttrs = Object.fromEntries(parseAttributes(open[1]).map(([n, v]) => [n.toLowerCase(), v]))

  let viewBox = rootAttrs.viewbox
  if (!viewBox) {
    const w = Number.parseFloat(rootAttrs.width)
    const h = Number.parseFloat(rootAttrs.height)
    if (!Number.isFinite(w) || !Number.isFinite(h)) {
      throw new Error('SVG needs a viewBox or a numeric width and height')
    }
    viewBox = `0 0 ${w} ${h}`
  }

  const body = svg.slice(open.index + open[0].length, close)
  const inner = body
    .replace(/<(\/?)([a-zA-Z][\w:-]*)([^>]*?)(\/?)>/g, (_tag, slash, name, rawAttrs, selfClose) => {
      if (UNWRAP_ELEMENTS.includes(name.toLowerCase())) return ''
      if (slash) return `</${name}>`
      return `<${name}${serialize(cleanAttributes(parseAttributes(rawAttrs)))}${selfClose ? '/' : ''}>`
    })
    .replace(/>\s+</g, '><')
    .trim()

  return { viewBox: viewBox.trim().replace(/\s+/g, ' '), inner }
}

/** Renders the generated SFC for one normalized icon. */
export function renderIconComponent({ source, viewBox, inner, mode = 'pixel' }) {
  const [, , gridWidth, gridHeight] = viewBox.split(' ')
  const paint =
    mode === 'stroke'
      ? `width="${STROKE_SIZE}" height="${STROKE_SIZE}" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" shape-rendering="geometricPrecision"`
      : `width="${gridWidth}" height="${gridHeight}" fill="currentColor" shape-rendering="crispEdges"`
  return [
    `<!-- Generated by scripts/build-icons.mjs from ${source}. Do not edit; run \`pnpm icons\`. -->`,
    '<template>',
    `  <svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" ${paint} aria-hidden="true" focusable="false">${inner}</svg>`,
    '</template>',
    '',
  ].join('\n')
}

function renderIndex(names) {
  const lines = [
    '// Generated by scripts/build-icons.mjs. Do not edit; run `pnpm icons`.',
    '// Named re-exports only: import the icons you use so the rest is tree-shaken.',
    ...names.map((name) => `export { default as ${name} } from './${name}.vue'`),
    '',
    `export const ICON_NAMES = [${names.map((n) => `'${n}'`).join(', ')}] as const`,
    '',
  ]
  return lines.join('\n')
}

/** Builds every icon into `outDir` (replacing its contents). Returns the written file names. */
export function buildIcons({ rootDir, outDir = join(rootDir, OUT_DIR), sourceDirs = SOURCE_DIRS }) {
  const icons = new Map()
  for (const { dir, mode } of sourceDirs) {
    const abs = join(rootDir, dir)
    if (!existsSync(abs)) continue
    for (const file of readdirSync(abs).filter((f) => f.toLowerCase().endsWith('.svg')).sort()) {
      const name = componentName(file)
      if (icons.has(name)) throw new Error(`Duplicate icon name ${name} (${dir}/${file})`)
      const source = relative(rootDir, join(abs, file)).split('\\').join('/')
      icons.set(name, { source, mode, ...normalizeSvg(readFileSync(join(abs, file), 'utf8')) })
    }
  }

  rmSync(outDir, { recursive: true, force: true })
  mkdirSync(outDir, { recursive: true })
  const names = [...icons.keys()].sort()
  const written = []
  for (const name of names) {
    writeFileSync(join(outDir, `${name}.vue`), renderIconComponent(icons.get(name)))
    written.push(`${name}.vue`)
  }
  writeFileSync(join(outDir, 'index.ts'), renderIndex(names))
  written.push('index.ts')
  return written
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isMain) {
  const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
  const written = buildIcons({ rootDir })
  console.log(`build-icons: wrote ${written.length} files to ${OUT_DIR}`)
}
